namespace Entities {
    /// <summary>
    /// Serves as the base class for all domain entities in the application.
    /// Provides a common identifier property to ensure all entities can be
    /// managed uniformly by the generic repository pattern.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This abstract class enforces a consistent identity model across all entities,
    /// which is required by the <c>IRepository&lt;T&gt;</c> generic constraint.
    /// </para>
    /// <para>
    /// Derived entity classes should focus on their specific domain properties
    /// while inheriting the <see cref="Id"/> property from this base class.
    /// </para>
    /// </remarks>
    public abstract class EntityBase {
        /// <summary>
        /// Gets or sets the unique identifier for this entity.
        /// </summary>
        /// <value>
        /// An integer value that serves as the primary key in the database.
        /// </value>
        /// <remarks>
        /// This property is typically auto-generated by the database using an identity column.
        /// </remarks>
        public int Id { get; set; }
    }
}
